" Be iMproved dammit
let &t_ut=''
set nocompatible
filetype off
set noswapfile
set clipboard=unnamedplus

nnoremap <silent> H :bprev<CR>
nnoremap <silent> L :bnext<CR>
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
nnoremap <CR> o<ESC>

" Unicode
set encoding=utf8

" Plugins
call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'rlgomes/vim-simpledb'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'Valloric/YouCompleteMe'
Plug 'altercation/vim-colors-solarized'
Plug 'mileszs/ack.vim'
Plug 'kien/ctrlp.vim'
Plug 'd11wtq/ctrlp_bdelete.vim'
Plug 'leafgarland/typescript-vim'
Plug 'stephpy/vim-yaml'
Plug 'w0rp/ale'
Plug 'rhysd/committia.vim'
Plug 'tpope/vim-speeddating'
Plug 'mxw/vim-jsx'
Plug 'mhinz/vim-startify'
Plug 'vimwiki/vimwiki'
Plug 'diepm/vim-rest-console'
Plug 'chriskempson/base16-vim'
Plug 'yssl/QFEnter'
call plug#end()
filetype plugin indent on

" let g_airline_theme='solarized'

" Ctrl-P
" let g:ctrlp_map = '<Leader>t'
nnoremap <C-b> :CtrlPBuffer<CR>
let g:ctrlp_match_window = 'bottom,order:ttb,min:1,max:30,results:30'
let g:ctrlp_max_files = 0
let g:ctrlp_by_filename = 1
call ctrlp_bdelete#init()
let g:ctrlp_open_multiple_files = 'ij'
let g:ctrlp_use_caching = 0

" Nerd Tree
nnoremap <silent> <C-N> :NERDTreeToggle<CR>
let g:NERDTreeDirArrows=0
let g:NERDTreeWinSize=35

" solarized colors
syntax enable
set background=dark
colorscheme solarized

" YouCompleteMe
inoremap <expr> <C-j> ("\<C-n>")
inoremap <expr> <C-k> ("\<C-p>")
let g:loaded_sql_completion = 0
let g:omni_sql_no_default_maps = 0
let g:ycm_semantic_triggers ={ 'elm' : ['.'] }
:set completeopt-=preview

" ag
let g:ackprg = 'ag --vimgrep --smart-case'
cnoreabbrev ag Ack!
cnoreabbrev aG Ack!
cnoreabbrev Ag Ack!
cnoreabbrev AG Ack!
cnoreabbrev Ack Ack!
nnoremap <silent><Leader>a :Ack <cword><cr>

" tab setup
:set tabstop=4
:set cindent
:set shiftwidth=4

" highlight cursor line
set cursorline

" show linenumbers
:set number
:set relativenumber

" keep cursor away from edge
set so=15

" column width
:set colorcolumn=100

" map leader to ,
:let mapleader = ","
:let maplocalleader = ","

" dont auto // comment 
au FileType * setlocal comments-=:// comments+=f://

" map space to write
:map <space> :w<CR>


" quickfix
nnoremap <silent><Leader>n :cn<cr>

" Allow JSX in normal JS files
let g:jsx_ext_required = 0

" 2 spaces for .json files for package.json
autocmd FileType json setlocal shiftwidth=2 tabstop=2 expandtab

" vimwiki
let g:vimwiki_list = [{'path': '~/vimwiki/', 'syntax': 'markdown', 'ext': '.md'}]

" vim-rest-console
let g:vrc_trigger = '<silent><Leader>r'

set wildignore=*.swp,*.class,*.jar,*.png,*.jpeg,*.jpg,**/node_modules/**,*.map,**/coverage/**,**/generated/**/*.d.ts,**/generated/**/*.js,**/src/**/*.d.ts,**/tests/**/*.d.ts,**/src/*.d.ts,build/**,**/*.tgz
let NERDTreeRespectWildIgnore=1
